### PR TITLE
Optimisation to 'parser.js' for large source files.

### PR DESCRIPTION
**Pull request by johnno1962**
Hi, been poking about looking at optimisations to the JS and found this one which seems to be important for overly large source files such as [this](https://github.com/johnno1962/siteify/blob/master/siteify/Siteify.swift). Creating a new DOM node and patching it into the existing tree seems a very expensive operation compared to just decorating the existing node.

### CODE REVIEW

**Comment by kishikawakatsumi** [comment]
@johnno1962 Thank you for the PR. 

> Creating a new DOM node and patching it into the existing tree seems a very expensive operation

Correct. But this operation is probably necessary. Because GitHub's source code view markup is dedicated to syntax highlighting, unhighlighted tokens are not enclosed by tags. It's just a text node.

Most events do not fire at text nodes. Many of the unhighlighted tokens are variables or custom types.
Your changes no longer display information from LSP for those variables and types. Because the hover event does not fire for such tokens.

Screen Shot 2020-04-12 at 23 01 15

(Here's an example. Hover events for `toolchainPath` do not work in the PR code.)

Creating a DOMElement for a text node is probably unavoidable.

To solve freezing UI, it might be good to split it into multiple chunks and run them asynchronously little by little instead of synchronously one path.

**Comment by johnno1962** [comment]
I see, Problematic. I figure all you can do is perform the line decoration in chunks of 100 lines. If it were possible to optimise the splicing in of the node, that’s where the bulk of the time is going.

**Comment by kishikawakatsumi** [comment]
Or, instead of processing everything in one pass, the first pass just extract the plain text (this is necessary for `didOpen`; without `didOpen`, all requests to the LSP will fail). Then add event listner to all tokens (= adding DOMElement) in the background thread.

**Comment by johnno1962** [comment]
Not sure I’m following you; Don’t you need the decoration for the hover to work? I've changed the PR to a version that extracts the text then decorates in chunks (slices) of 100 separated by 100ms. Loads quickly but with slightly degraded interactivity while it completes the file.

**Comment by kishikawakatsumi** [comment]
Looks good, thanks!

**Pull request merged**
